apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  selector:
    svc2pod: wordpress
  ports:
  - port: 30000
    targetPort: http
  sessionAffinity: ClientIP
  type: LoadBalancer